# Generated by Django 5.2.7 on 2025-11-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0002_team_profile_teammember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="photo",
        ),
        migrations.CreateModel(
            name="TweetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/")),
                (
                    "tweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tweet.tweet",
                    ),
                ),
            ],
        ),
    ]
